import type { Metadata } from "next";
import SessionWrapper from "@/components/SessionWrapper";
import BootstrapClient from "@/app/components/bootstrap/bootstrap";
import Header from "./components/Headers";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

  
export const metadata: Metadata = {
  title: "VRV Administrator !",
  description: "Generated by requester....",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <SessionWrapper>
      <body  className="bg-theme bg-theme3 nunito-body">
        <Header />
        <div className="content-body">
            <div className="container">
                {children}
            </div>
        </div>
        <ToastContainer />
        <BootstrapClient />

      </body>
      </SessionWrapper>
    </html>
    
  );
}
